/* DO NOT MODIFY: automatically generated by cbindgen */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

#define RISCV_DRIVER_BASE_ADDRESS 4060086272

void rust_main(void);

extern void print_char(char c);

extern void test_write32(uint32_t value);

extern uint32_t test_read32(void);

extern void set_leds(uint32_t mask);

extern uint64_t get_native_time(void);

extern float diff_native_time(uint64_t start, uint64_t end);

void set_leds(uint32_t mask);

void print_char(char _c);

void test_write32(uint32_t _value);

uint32_t test_read32(void);
