/* DO NOT MODIFY: automatically generated by cbindgen */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

#define RISCV_DRIVER_BASE_ADDRESS 4060086272

typedef struct Conflict {
  uint16_t node_1;
  uint16_t node_2;
  uint16_t touch_1;
  uint16_t touch_2;
  uint16_t vertex_1;
  uint16_t vertex_2;
} Conflict;

typedef struct Obstacle {
  uint16_t grown;
  struct Conflict conflict;
} Obstacle;

void rust_main(void);

extern void print_char(char c);

extern void test_write32(uint32_t value);

extern uint32_t test_read32(void);

extern void set_leds(uint32_t mask);

extern uint64_t get_native_time(void);

extern float diff_native_time(uint64_t start, uint64_t end);

extern struct Obstacle find_obstacle(void);
